version: 2.1

orbs:
  sfdx: circleci/salesforce-sfdx@dev:alpha
  orb-tools: circleci/orb-tools@8.27.3

jobs:
  install_cli_tar:
    executor: sfdx/default
    working_directory: ~/project/sample
    steps:
      - sfdx/install
  install_cli_npm:
    executor: sfdx/default
    working_directory: ~/project
    steps:
      - sfdx/install:
          version: latest
  install_authenticate:
    executor: sfdx/default
    working_directory: ~/project
    steps:
      - sfdx/install
      - sfdx/auth:
          defaultusername: community-partner@circleci.com
      - run:
          name: Check Auth List
          command: sfdx force:auth:list
  scratch_functions:
    executor: sfdx/default
    working_directory: ~/project
    steps:
      - sfdx/install
      - sfdx/auth:
          defaultusername: community-partner@circleci.com
      - sfdx/scratch-create:
          scratch-config: "./sample/scratch-def.json"
          scratch-alias: "circleci"
      - sfdx/scratch-open:
          scratch-alias: "circleci"
      - sfdx/scratch-delete:
          scratch-alias: "circleci"

# yaml anchor filters
prod-deploy_requires: &prod-deploy_requires
  [
    install_cli_tar-master,
    install_cli_npm-master,
    install_authenticate-master,
    scratch_functions-master,
  ]

integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

workflows:
  # this `lint-pack_validate_publish-dev` workflow will run on any commit
  lint-pack_validate_publish-dev:
    jobs:
      # lint your destructured orb YAML files
      - orb-tools/lint

      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack:
          requires:
            - orb-tools/lint

      # release dev version of orb, for testing & possible publishing
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: circleci/salesforce-sfdx
          requires:
            - orb-tools/pack

      # trigger an integration workflow to test the dev version of your orb
      # an SSH key must be stored in your orb's repository and in CircleCI
      # (add the public key as a read/write key on GitHub; add the private
      # key in CircleCI via SSH Permissions, with github.com as Hostname)
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          ssh-fingerprints: af:51:88:95:26:d1:4c:8a:7b:16:da:12:25:ce:ec:40
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      # by default, the 1st job (above) will trigger only integration tests;
      # the 2nd job (below) may also publish a production orb version
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          cleanup-tags: true
          ssh-fingerprints: af:51:88:95:26:d1:4c:8a:7b:16:da:12:25:ce:ec:40
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  # this `integration-tests_prod-release` workflow will ignore commits
  # it is only triggered by git tags, which are created in the job above
  integration-tests_prod-release:
    jobs:
      # - your integration test jobs go here
      # - you will want to call each integration testing job twice,
      # - each under a different name:
      # - once, for integration tests triggered by non-master-branch commits
      # - and again, for tests triggered by commits to master
      # - only commits to master should potentially trigger a prod release

      - install_cli_tar:
          name: install_cli_tar-dev
          filters: *integration-dev_filters
      - install_cli_tar:
          name: install_cli_tar-master
          filters: *integration-master_filters
      - install_cli_npm:
          name: install_cli_npm-dev
          filters: *integration-dev_filters
      - install_cli_npm:
          name: install_cli_npm-master
          filters: *integration-master_filters
      - install_authenticate:
          name: install_authenticate-dev
          filters: *integration-dev_filters
      - install_authenticate:
          name: install_authenticate-master
          filters: *integration-master_filters
      - scratch_functions:
          name: scratch_functions-dev
          filters: *integration-dev_filters
      - scratch_functions:
          name: scratch_functions-master
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: circleci/salesforce-sfdx
          ssh-fingerprints: af:51:88:95:26:d1:4c:8a:7b:16:da:12:25:ce:ec:40
          cleanup-tags: true
          requires:
            *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          orb-name: circleci/salesforce-sfdx
          ssh-fingerprints: af:51:88:95:26:d1:4c:8a:7b:16:da:12:25:ce:ec:40
          cleanup-tags: true
          requires:
            *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          orb-name: circleci/salesforce-sfdx
          ssh-fingerprints: af:51:88:95:26:d1:4c:8a:7b:16:da:12:25:ce:ec:40
          cleanup-tags: true
          requires:
            *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
