# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  'Base CircleCI cimg convenience Docker image. This image is small, highly cached, and contains the minimum nessecary components needed for CI. Learn more: https://github.com/CircleCI-Public/cimg-base'
docker:
  - image: 'cimg/node:<<parameters.tag>>'
parameters:
  tag:
    default: stable
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node
    type: string
