# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  'cimg/node is a Docker image created by CircleCI with continuous integration builds in mind. Each tag contains a version of Node.js, npm, yarn, and any binaries and tools that are required for builds to complete successfully in a CircleCI environment. https://github.com/CircleCI-Public/cimg-node'
docker:
  - image: 'cimg/node:<<parameters.tag>>'
parameters:
  tag:
    default: "14.7"
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node
    type: string
